use_frameworks!

target 'SDWebImageSVGKitPlugin_Example' do
  platform :ios, '9.3'
  pod 'SDWebImageSVGKitPlugin', :path => '../'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
end

target 'SDWebImageSVGKitPlugin_Example macOS' do
  platform :osx, '10.13'
  pod 'SDWebImageSVGKitPlugin', :path => '../'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
end