use_frameworks!

platform :ios, '8.0'

target 'SDWebImageSVGKitPlugin_Example' do
  pod 'SDWebImageSVGKitPlugin', :path => '../'

  target 'SDWebImageSVGKitPlugin_Tests' do
    inherit! :search_paths

    
  end
end
